version: "3.9"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.21
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306


